### ISSUE TITLE
"Your Emacs was not compiled with xwidgets support"

### ISSUE THREAD

**Issue by AtomicNess123** [jakebox/preview-org-html-mode#1]
I am getting this error unfortunately.

**Comment by jakebox** [comment]
Hi, that issue means that, well, your Emacs was not compiled with Xwidgets support. You'll need to recompile/reinstall your Emacs. How to do this depends on what platform you're on. I'd say do a search for how to do this for your specific platform. I can only help with Mac OS unfortunately. Good luck!

**Comment by AtomicNess123** [comment]
I use MAC OS fortunately!

**Comment by jakebox** [comment]
In that case, you can build `emacs-plus` with xwidgets support by doing `brew install emacs-plus --with-xwidgets`.

**Comment by AtomicNess123** [comment]
Thanks. Will this affect my other config? I use prelude.

**Comment by jakebox** [comment]
Nope, everything should be fine!
